server:
  port: 9999

spring:
  application:
    name: uaa
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        ipAddress: 10.0.75.1
        preferIpAddress: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckPath:  /actuator/health
        healthCheckInterval: 15s

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.yml

logging:
  level:
    root: WARN
    logging.level.org.springframework.web: DEBUG
    org.springframework.security: DEBUG