version: "3.1"

networks:
  web:
    driver: bridge

services:
  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  db-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

  consul:
    image: bitnami/consul:latest
    networks:
    - web
    ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8500:8500
    - 8600:8600
    - 8600:8600/udp

  traefik:
    image: traefik:latest
    restart: always
    command: --api --docker
    ports:
    - 80:80
    - 443:443
    - 8080:8080
    volumes:
    - ./traefik.toml:/traefik.toml
    networks:
    - web

#  uaa:
#    image:
#    healthcheck:
#      test: wget -q --spider $$(hostname -i):8080/uaa/actuator/health
#      interval: 10s
#      timeout: 360s
#      retries: 50
#    ports:
#    - "11000:8080"
#    depends_on:
#    - postgres
