################################################################
# Consul Catalog configuration backend
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8080"

# Enable Consul Catalog configuration backend
[consulCatalog]

# Consul server endpoint
#
# Required
#
endpoint = "10.0.75.1:8500"

# Default domain used.
#
# Optional
#
domain = "consul.localhost"

# Expose Consul catalog services by default in traefik
#
# Optional
#
exposedByDefault = false

# Prefix for Consul catalog tags
#
# Optional
#
prefix = "traefik"
